#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

ENGINE_ROOT = File.expand_path('../..', __FILE__)
ENGINE_PATH = File.expand_path('../../lib/voshod_avto_1c_exchange/engine', __FILE__)

require 'rails/all'
require 'rails/engine/commands'
